# Generated by Django 3.2.22 on 2024-04-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='c_number',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
