# Generated by Django 3.2.22 on 2024-04-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='CUSTOMER',
        ),
        migrations.AddField(
            model_name='payment',
            name='STAFF',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.staff'),
        ),
    ]
