# Generated by Django 2.1.7 on 2024-03-27 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='SUBSCRIPTION_LIST',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='p_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='p_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='STAFF',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='month',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='year',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(),
        ),
    ]
