# Generated by Django 2.1.7 on 2024-03-27 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20240327_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('p_date', models.CharField(max_length=20)),
                ('p_status', models.CharField(max_length=20)),
                ('SUBSCRIPTION_LIST', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App.subscription_list')),
            ],
        ),
    ]
