# Generated by Django 3.2.22 on 2024-04-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20240420_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_list',
            name='valid_upto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
