# Generated by Django 2.1.7 on 2024-04-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_collection_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='a_time',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
