# Generated by Django 2.1.7 on 2024-04-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_attendance_a_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='a_time',
        ),
    ]
