# Generated by Django 2.1.7 on 2024-04-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_attendance_a_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='s_credited',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
